### PR TITLE
Styling for Scavenger Hunt

### PR DESCRIPTION
**Pull request by varunnaik**
Styling for the scavenger hunt page.

While this follows the Figma design for the most part, it does deviate slightly.
* No blue header
* There is a black bar between header and content (seems to come from elsewhere in layout)
* Questions repeated on side

I am not 100% confident that the text overlaid on top of the notebook will retain its layout at all resolutions/on all screens so I have repeated the questions in the sidebar as well.

The design is not responsive and the text overlay above the notebook cannot be made to work in a responsive way. This does not use Bootstrap but it does not need Bootstrap except for the 'View Instructions' button.

image

### CODE REVIEW

**Comment by ooliviarr** [comment]
Thanks! With the blue bar, could we get that added in somehow. If you check out the other figma mockups you'll see that the blue/red bar is a new thing that will be on top of most pages - so good if we can be consistent.

**Comment by varunnaik** [comment]
Please push to your branch, unless there will be conflicts. We can merge this (into your branch, scavenger-hunt, not main) as soon as I have added the blue header if there are no further changes needed.

The black bar in the screenshot comes from the top bar which has a 3em border-bottom defined (top_bar.scss, line 5). Though it is not part of the scavenger hunt design I cannot remove it without affecting global styles so I am not changing it.

**Comment by varunnaik** [comment]
Hi @cassar I can't add the blue header as such because it is on master.
I suggest we merge this branch into yours then rebase your branch against master (or merge master in if you prefer) so we get the blue header code. Then I can create a new branch off of that to add the header and style the badges after you implement them.

**Comment by cassar** [comment]
Hey Varun, have rebased the scavenger-hunt branch with main (our 'master'), made some more changes to the controller (assigning a badge when all questions have been answered). 

I was not able to rebase to this PR/Branch however as it appeared to be based off main branch rather than the scavenger-hunt branch, not sure what Github is doing here. But I cherry-picked your two commits from this PR to scavenger hunt and everything seems to be working as before.

**Pull request closed without merging**
