### PR TITLE
CSS Tweaks

### PR DESCRIPTION
**Pull request by varunnaik**
- Adds the blue header to all pages. Have tweaked CSS to allow this.
- Sticky footer
- Slightly improved shadows on header

I am reasonably sure that I've got all the pages, that said I might've missed a few pages in which case they will display the old header.

Old:
image

New:
image

### CODE REVIEW

**Comment by developerpeachy** [comment]
Hey, @varunnaik this is awesome!

Just echo-ing with Luke, this should be added to the main pages rather than all the pages, perhaps you could add this to these pages instead? Also, probably best not to touch the main.scss or the root one until we have a solid design system :) 

- Challenges index 
- Events index
- Projects index 
- Resources index 

Thank you for doing this!!

**Comment by varunnaik** [comment]
Hi @cassar @developerpeachy 
Agreed, changing the global H2 style was a bit of a gamble. I'll find some time later today to apply this only to the pages mentioned (and their child-pages).

Note that I've applied a display:flex on the <body> tag, this is to enable the sticky footer. Can't have sticky footer without this (at least not in an elegant way) - I'll double check that this is not the cause of the layout breakage on admin pages. Any specific pages that were observed to be broken?

**Comment by cassar** [comment]
Hey Varun, 

As I said, it's affected most of the admin pages, have a look at http://localhost:3000/admin/competitions/1

**Comment by varunnaik** [comment]
Hey, so this is proving difficult to do because the pages have a padding on their root container which is shared across all pages in each of the 4 modules listed (i.e., the index page and all children) - so applying the change only to the index but not the child pages is not possible.

I'll do a final attempt over the next two days and see if I can make something robust work, otherwise it is probably best to abandon this attempt.

**Comment by cassar** [comment]
No worries, thanks for having a go 👍

**Comment by varunnaik** [comment]
I am closing this, the only way to add a blue header that isn't a complete hack is to refactor the CSS for the whole site to use global styles across all pages. This is best done once we have a design system as @developerpeachy suggests.

**Pull request closed without merging**
