### PR TITLE
Add Mailchimp Subscriber to List

### PR DESCRIPTION
**Pull request by cassar**
## Background

Relates to #252

Having trouble with this at the moment, keep getting an error (see the code at mailchimp.rb to see what I was running)

> Error: {"type":"https://mailchimp.com/developer/marketing/docs/errors/","title":"Invalid Resource","status":400,"detail":"The resource submitted could not be validated. For field-specific details, see the 'errors' array.","instance":"9f7949bd-9afc-10ec-1545-d6d041cec6e0","errors":[{"field":"email_address","message":"This value should not be blank."}]}

Is anyone able to see if they can get it working?

Mailchimp docs very good. https://mailchimp.com/developer/marketing/api/list-members/add-member-to-list/

Can be done in BASH, PHP, PYTHON, or NODE also. 

Screen Shot 2021-06-16 at 8 11 58 am

Will need to open your own Mailchimp account and get an API key etc.

### CODE REVIEW

**Comment by karwalski** [comment]
I was able to reproduce your error message when passing the email as either a parameter or as form data in the body.

Using postman, I was also able to successfully update a subscriber to the list by sending the email address in a JSON object in the body, like:

`{
    "email_address": "Kelley.Haley28@hotmail.com",
    "status": "subscribed",
    "merge_fields": {
        "FNAME": "Kelley",
        "LNAME": "Haley"
    }
}`

It responds with a HTTP 200 status code, and body like

`{
    "id": "XXX",
    "email_address": "Kelley.Haley28@hotmail.com",
    "unique_email_id": "XXX",
    "full_name": "Kelley Haley",
    "web_id": XXX,
    "email_type": "html",
    "status": "subscribed",
    ...
}`

The object in mailchimp.rb looks correct, maybe some kind of conflict with the multiple JSON libraries included. Have you tried without the merge fields so that it is a single level object/array.


Otherwise, you 'should' be able to pass the a JSON string directly as the Mailchimp code won't try convert it to JSON if it is already a string.
https://github.com/mailchimp/mailchimp-marketing-ruby/blob/f95a4b4a5f077c1db05f760e39c3b8f85ed1c2fc/lib/MailchimpMarketing/api_client.rb#L85

**Comment by cassar** [comment]
@karwalski , looks like it was the (official) gem that was bad 🤷🏻‍♂️

Using another one that I found which appears to be working.

Can set it up to only add after the user has confirmed their email, currently users have 1 day to confirm their email and wander the hackerspace before they lose access and have to confirm.

**Comment by cassar** [comment]
Will make fresh PR

**Comment by cassar** [comment]
#280

**Pull request closed without merging**
