### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by mattcen**
Fix a bunch of typos in views.

NOTE: I updated "GRAVITAR" to "GRAVATAR" and I searched for and found all instances of that typo, but didn't actually check that it doesn't break things.

### CODE REVIEW

**Comment by mattcen** [comment]
I used [cSpell](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) to check for errors in *all* of the `.haml` files in `views/`, ignoring a bunch of typos that were in code rather than being displayed on the website.

**Comment by mattcen** [comment]
Just realised I'd accidentally committed a file I'd not intended, and have now removed it from this merge.

The change was the following, to `app/views/layouts/_footer.html.haml`:
```diff
+  %p
+    The
+    %em GovHack Hackerspace
+    is licensed under the AGPL3. Its source code is available a{ :href => "https://github.com/govhackaustralia/hackerspace3/", :title => "on GitHub" }.
```

I'd like to get that change committed if possible, but I couldn't get the syntax for the hyperlink to work because my Haml-fu is weak.

**Comment by cassar** [comment]
@mattcen , try a new line, I'd like to see that in too.
```haml
+  %p
+    The
+    %em GovHack Hackerspace
+    is licensed under the AGPL3. Its source code is available 
      %a{ href: "https://github.com/govhackaustralia/hackerspace3/", title: "on GitHub" }
```

**Comment by mattcen** [comment]
Sweet; I got there eventually! Fixed in #180.

**Pull request merged**
